services:

  fiesta_app:
    build: ./app
    ports:
      - "8000"

  fiesta_nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:8000"
    depends_on:
      - fiesta_app